"""State target semantics, matched controls, scale and vintage limits explicitly."""
import json
import re
import pandas as pd
from scripts.phase6g3.protection import OUT


def markdown_paragraphs(text):
    """Keep table rows contiguous while separating explanatory paragraphs."""
    text=re.sub(r'\n{3,}','\n\n',text)
    return re.sub(r'(?m)^(\|[^\n]*\|)\n\n(?=\|)',r'\1\n',text)


def write_report(audit,gdp,comparison,metrics,now,failures,diagnostics):
    classification='PHASE6G3_TARGET_DEFINITION_ISSUE_FOUND'
    c=comparison.set_index('model');n=c.loc['NOMINAL_STANDALONE_LOG'];r=c.loc['REAL_SHARED_BRIDGE']
    lines=['# Phase 6G.3 — GDP target audit and nominal challenger','',classification,'',
        '**Production remains unchanged.** The current real target is cumulative-period YTD real GDP YoY growth reported at quarter ends. It is not standalone-quarter real GDP YoY. All 34 SIAT-to-processed-to-master observations reconcile. This is a period-definition limitation, not an arithmetic/parser bug or an unauthorized registry correction.',
        '', '| Model / target | N | H1 RMSE | H2 RMSE | H3 RMSE | Pooled RMSE | Target SD | Normalized RMSE | 2026Q3 |',
        '|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for row in comparison.itertuples(index=False):
        lines.append(f'| {row.model} | {row.N} | {row.H1_RMSE:.6f} | {row.H2_RMSE:.6f} | {row.H3_RMSE:.6f} | {row.RMSE:.6f} | {row.target_std:.6f} | {row.normalized_RMSE:.6f} | {row.nowcast:.6f} |')
    lines+=['','## A. Real-GDP lineage and definition','',
        '[Official SIAT real GDP growth dataset 3698](https://siat.stat.uz/data/3698/?lang=en), indicator **1.01.01.0059**, exact national selector `Code=1700`, `Klassifikator_en=Republic of Uzbekistan`. The registry routes the official descriptor to its linked archived JSON. The parser validates dimensions, code, unit and quarterly frequency; `gdp_target` subtracts 100; the result is stored in processed GDP and the separate quarterly master.',
        'The archived dated national reports explicitly say January–March, January–June, January–September and January–December. Their real growth chart values match the cumulative-period convention recorded in Phase 6B.2. SIAT’s quarterly frequency is a reporting frequency; it does not make Q2–Q4 standalone-quarter observations. Q1 is both the first quarter and the first YTD period.',
        f'`gdp_target_audit.csv` inspects {len(audit)} quarters from 2018Q1 through 2026Q2, retaining raw index, source definition, model/current-master target, exact transformation, first-release evidence where verified, current revised status, retrieval/update dates and checksums. {int(audit.first_release_date.isna().sum())} first-release dates remain unresolved. Dataset update timestamps are never used as those first releases.',
        'Historical model training does not simply use the current master: the existing strict accessor selects latest documented official growth vintages available before each origin. Frozen historical actuals are retained exactly. Origin-specific training values and the raw/master lineage are therefore separate parts of the audit.',
        '**Finding:** implementation conforms to the existing index-minus-100 registry rule. The conceptual issue is calling this a standalone-quarter GDP growth target, or interpreting its forecast that way. This cumulative convention was already documented in Phase 6B.2; Phase 6G.3 verifies it across the full series. The classification records this semantic issue, without claiming a newly introduced production bug.',
        'Proposed clarification for deliberate future registry review: explicitly name/describe the target as cumulative YTD real GDP YoY at quarterly reporting frequency. Recover official standalone-quarter real volume levels or appropriate weights before constructing a standalone-real target. Never de-cumulate real growth percentages or subtract Q1 growth from H1 growth.',
        '','## B–C. Nominal levels, validation and growth','',
        '[Official SIAT nominal GDP dataset 3695](https://siat.stat.uz/data/3695/?lang=en), indicator **1.01.01.0056**, production method, current prices, national currency **billion UZS**. The quarterly table is cumulative within the calendar year. Descriptor and payload bytes are immutable in this phase’s raw directory with URL, retrieval time, status, checksum, parser version and schema fingerprint.',
        'The standalone flow is Q1=cumulative Q1, Q2=H1−Q1, Q3=9M−H1, Q4=FY−9M, strictly within year. Both cumulative and standalone values are retained. Missing prior quarters produce missing flow; no filling occurs. Growth is `100*(ln(standalone_t)-ln(standalone_t-4))`; conventional `100*(standalone_t/standalone_t-4-1)` is separately retained. The growth percentage itself is never logarithmized.',
        f'The revised SIAT dataset has {len(gdp)} levels and {int(gdp.nominal_gdp_yoy_log.notna().sum())} usable standalone YoY log targets. No standalone value is nonpositive. Complete-year standalone sums are independently checked against [official annual SIAT dataset 544](https://siat.stat.uz/data/544/?lang=en), indicator 1.01.01.0001. All complete 2018–2025 years pass; 2026 is incomplete and has no annual test. The first four growth values are missing because a prior-year standalone quarter is absent.',
        'Revisions are preserved in `nominal_cumulative_vintage_events.csv` and `nominal_growth_vintage_history.csv`. The latest SIAT snapshot is used for descriptive/current-series validation only; its revised values never receive historical release dates.',
        '','## D. Controlled experiment and information sets','',
        'The accepted factor extractor is reused exactly: the same eight predictors and transformations, economic M2 lag zero, one DynamicFactorMQ factor, AR(2), no idiosyncratic AR(1), EM maxiter 500/tolerance 1e−5, training-only scaling, balanced start and ragged-edge release masks. Filtered factor paths and loadings are identical for both target bridges by construction. The accepted real bridge is independently reproduced against every frozen historical/current prediction to tolerance 1e−7.',
        'Nominal targets are derived only from dated official publication events. At each historical origin, every cumulative parent is the latest documented level with publication date strictly earlier than that origin; target/future quarters are excluded. All four required parent values and publication dates/checksums/URLs are recorded. Revisions to a cumulative parent also revise derived standalone levels and growth. No registry lag substitutes for an unknown release date.',
        'The archive is partial. Early nominal 2018Q1/Q2 publication values are absent; derived growth begins only once its published parents are known. A dated FY2023 article reports **1,066.6 trillion UZS**, converted to **1,066,600 billion UZS**, with 100-billion reporting precision explicitly flagged. It is a rounded published value, never presented as an exact SIAT vintage. The reviewed extraction ledger is tied to checksummed official PDFs/HTML.',
        'Cumulative parents from different dated releases may reflect different revision vintages. That is the information actually available under this partial archive, not a coherent complete provider snapshot. Mixed vintages and rounded parents are flagged. GDP methodological/non-observed-economy revisions can create unusually large derived quarterly changes; interpret these as a limitation rather than proof of economic acceleration.',
        'Both controlled bridges use intercept + quarterly mean accepted factor + their own target’s GDP-growth(q−1). Their training quarter set is the **same intersection** of documented real and nominal target histories, inside the unchanged estimation window. `REAL_SHARED_BRIDGE` controls for the reduced nominal data coverage. `ACCEPTED_REAL_DFM` retains its original full real bridge for reference. This additional common-target restriction is necessary for a fair experiment and is explicitly not identical to the full accepted real training sample.',
        f'All 44 accepted historical origins are attempted. {int(n.N)} origins form the exact three-model common evaluation sample. {len(failures)} historical/current controlled-origin failures are retained in `model_failures.csv`; insufficient nominal history is never silently replaced. The minimum bridge training requirement remains 12 quarters.',
        '**Identification limit:** the requested real-to-nominal comparison also changes cumulative real growth to standalone nominal growth, and ordinary percentage growth to log growth. It therefore does not isolate inflation alone. Cumulative nominal and log-real YTD diagnostics are supplied to separate period definitions descriptively, without redesigning the DFM.',
        '','## E. Forecast performance and scale','',
        f'Normalized RMSE is {r.normalized_RMSE:.6f} for the real shared bridge and {n.normalized_RMSE:.6f} for nominal standalone growth. Nominal appears '+('better' if n.normalized_RMSE<r.normalized_RMSE else 'worse')+' on this scale-adjusted measure; raw percentage-point RMSEs across the two targets are not evidence of inherent target superiority.',
        'Target SD uses unique target quarters within each horizon/sample. Forecast volatility is the sample SD of origin predictions. MAE, actual-minus-forecast bias, forecast correlation, forecast R² relative to that target’s realized sample mean and OOS R² relative to the released GDP-growth(q−1) naive forecast are in `horizon_metrics.csv`. These are within-target measures; forecast correlation or in-sample associations alone do not establish useful nowcast accuracy.',
        'Nominal evaluation actuals are **first documented derived** standalone-growth values from the dated archive, not certified exhaustive first-release nominal targets. Real actuals are exactly those of the existing clean evaluation. Largest misses by model are in `largest_historical_misses.csv`; actual publication and parent provenance are separately stored.',
        '','## F. Real activity versus inflation information','',
        'The accepted factor has M2, PPI, USD/UZS, RUB/UZS, gold prices, industrial production, ex-gold reserves and verified-scope POS turnover. CPI, retail, wholesale, exports and imports are supplementary economic diagnostics only; their DFM loading is unavailable because they do not enter the accepted factor. Nominal/real GDP enter the quarterly bridge, not the factor panel. No missing loading is invented.',
        'Correlations use quarter means with all three observed months and preserve gaps. CPI/PPI YoY log inflation is the sum of 12 monthly log changes, requiring all 12 observations. `target_diagnostics.csv` compares each predictor with standalone nominal growth, cumulative nominal log growth, real YTD growth and an implicit YTD price-growth component.',
        'The implicit price component is the difference between nominal YTD log growth and real YTD log growth on the latest revised series; it is a descriptive decomposition, not a separately recovered official vintage deflator. Ex-post factor regressions on real growth, price growth and both quantify associations only. They cannot prove that inflation causes forecast performance.',
        '','## Current 2026Q3 research estimates','']
    for row in now.itertuples(index=False):lines.append(f'{row.model}: {row.nowcast:.9f}, {row.unit}; {row.status}.')
    lines+=['','The nominal nowcast is a nominal standalone-quarter YoY log growth forecast. It cannot be subtracted from the real cumulative growth forecast and interpreted as a revision or price effect. Production DFM, U-MIDAS and COMBO_50_50 numbers are preserved.',
        '','## Conclusion and reproduction','',
        'The real target construction is arithmetically consistent and registry-compliant, with a confirmed cumulative-period interpretation. The nominal dataset validates, and a controlled partial-archive challenger is estimable on the matched subset. Period-definition differences, incomplete nominal release history and mixed parent revisions prevent a clean price-basis-only superiority claim. No production promotion or target alteration is authorized by these results.',
        'Run `.venv/Scripts/python.exe -m scripts.phase6g3.run`; test `.venv/Scripts/python.exe -m scripts.phase6g3.tests`. Re-runs reuse checksummed archived nominal SIAT downloads. All authoring is confined to scripts/phase6g3 and results/phase6g3. Before/after protected hashes and test summaries are stored in this phase.']
    assoc=diagnostics.loc[diagnostics.diagnostic_type.eq('EX_POST_FACTOR_COMPONENT_ASSOCIATION')]
    lines+=['','Ex-post factor associations: '+ '; '.join(f'{r.indicator} R²={r.R2:.6f}, N={r.N}' for r in assoc.itertuples())+'.']
    associations=diagnostics.loc[diagnostics.diagnostic_type.eq('EX_POST_QUARTERLY_ASSOCIATION')].set_index('indicator')
    lines+=['','| Indicator | Corr. nominal standalone log YoY | Corr. real YTD log YoY | Corr. implicit YTD price growth |',
            '|---|---:|---:|---:|']
    for key in ['m2','cpi','ppi','retail','wholesale','exports','imports','usd_uzs','rub_uzs','industrial_production','accepted_filtered_factor']:
        row=associations.loc[key]
        lines.append(f'| {key} | {row.correlation_with_nominal_gdp_yoy_log:.6f} | {row.correlation_with_real_gdp_ytd_yoy_log:.6f} | {row.correlation_with_implicit_YTD_price_log_growth:.6f} |')
    lines.append('The nominal model is weaker on normalized RMSE, so these results do not support an inflation-driven nominal accuracy advantage. PPI and CPI do contain price information, while industrial production shows a stronger real-growth association. The accepted factor’s price-only association is weak compared with real-only association; both together add little explanatory power in this ex-post diagnostic. Interpretation remains descriptive and sensitive to target revisions/period definitions.')
    if not failures.empty:lines.append('Failed origins: '+str(failures[['target_quarter','horizon','current','error']].to_dict('records')))
    (OUT/'phase6g3_results.md').write_text(markdown_paragraphs('\n\n'.join(lines)+'\n'),encoding='utf8')
    return classification
